
%Bilge OKCU
% Define images to process
imageFileNames1 = {'calib_stereo_1\left\left-0000.png',...
    'calib_stereo_1\left\left-0001.png',...
    'calib_stereo_1\left\left-0002.png',...
    'calib_stereo_1\left\left-0003.png',...
    'calib_stereo_1\left\left-0004.png',...
    'calib_stereo_1\left\left-0005.png',...
    'calib_stereo_1\left\left-0006.png',...
    'calib_stereo_1\left\left-0007.png',...
    'calib_stereo_1\left\left-0008.png',...
    'calib_stereo_1\left\left-0009.png',...
    'calib_stereo_1\left\left-0010.png',...
    'calib_stereo_1\left\left-0011.png',...
    'calib_stereo_1\left\left-0012.png',...
    'calib_stereo_1\left\left-0013.png',...
    'calib_stereo_1\left\left-0014.png',...
    'calib_stereo_1\left\left-0015.png',...
    'calib_stereo_1\left\left-0016.png',...
    'calib_stereo_1\left\left-0019.png',...
    'calib_stereo_1\left\left-0020.png',...
    'calib_stereo_1\left\left-0021.png',...
    'calib_stereo_1\left\left-0022.png',...
    'calib_stereo_1\left\left-0023.png',...
    'calib_stereo_1\left\left-0025.png',...
    'calib_stereo_1\left\left-0028.png',...
    'calib_stereo_1\left\left-0029.png',...
    'calib_stereo_1\left\left-0036.png',...
    'calib_stereo_1\left\left-0037.png',...
    'calib_stereo_1\left\left-0038.png',...
    'calib_stereo_1\left\left-0040.png',...
    'calib_stereo_1\left\left-0041.png',...
    'calib_stereo_1\left\left-0042.png',...
    'calib_stereo_1\left\left-0043.png',...
    'calib_stereo_1\left\left-0044.png',...
    'calib_stereo_1\left\left-0045.png',...
    };
imageFileNames2 = {'calib_stereo_1\right\right-0000.png',...
    'calib_stereo_1\right\right-0001.png',...
    'calib_stereo_1\right\right-0002.png',...
    'calib_stereo_1\right\right-0003.png',...
    'calib_stereo_1\right\right-0004.png',...
    'calib_stereo_1\right\right-0005.png',...
    'calib_stereo_1\right\right-0006.png',...
    'calib_stereo_1\right\right-0007.png',...
    'calib_stereo_1\right\right-0008.png',...
    'calib_stereo_1\right\right-0009.png',...
    'calib_stereo_1\right\right-0010.png',...
    'calib_stereo_1\right\right-0011.png',...
    'calib_stereo_1\right\right-0012.png',...
    'calib_stereo_1\right\right-0013.png',...
    'calib_stereo_1\right\right-0014.png',...
    'calib_stereo_1\right\right-0015.png',...
    'calib_stereo_1\right\right-0016.png',...
    'calib_stereo_1\right\right-0019.png',...
    'calib_stereo_1\right\right-0020.png',...
    'calib_stereo_1\right\right-0021.png',...
    'calib_stereo_1\right\right-0022.png',...
    'calib_stereo_1\right\right-0023.png',...
    'calib_stereo_1\right\right-0025.png',...
    'calib_stereo_1\right\right-0028.png',...
    'calib_stereo_1\right\right-0029.png',...
    'calib_stereo_1\right\right-0036.png',...
    'calib_stereo_1\right\right-0037.png',...
    'calib_stereo_1\right\right-0038.png',...
    'calib_stereo_1\right\right-0040.png',...
    'calib_stereo_1\right\right-0041.png',...
    'calib_stereo_1\right\right-0042.png',...
    'calib_stereo_1\right\right-0043.png',...
    'calib_stereo_1\right\right-0044.png',...
    'calib_stereo_1\right\right-0045.png',...
    };

[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames1, imageFileNames2);

squareSize = 25; 
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

I1 = imread('calib_stereo_1\left\left-0000.png');
[mrows, ncols, ~] = size(I1);

% Calibrate the camera
[stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(stereoParams);

% Visualize pattern locations
h2=figure; showExtrinsics(stereoParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, stereoParams);

% You can use the calibration data to rectify stereo images.
I2 = imread('calib_stereo_1\right\right-0000.png');

[J1, J2] = rectifyStereoImages(I1, I2, stereoParams);

dispRange = [0, 160]; %MinDisparity, MaxDisparity
disparityMap = disparity(J1, J2, ...
    'DisparityRange', dispRange, ...
    'BlockSize', 15, ...
    'ContrastThreshold', 0.5, ...
    'UniquenessThreshold', 15 );
	
% show disparity map
figure 
imshow(disparityMap, dispRange);
colormap(gca,jet) 
colorbar


points3D = reconstructScene(disparityMap, stereoParams);

% expand gray image to three channels (simulate RGB)
J1_col = cat(3, J1, J1, J1);

% Convert to meters and create a pointCloud object
points3D = points3D ./ 1000;
ptCloud = pointCloud(points3D, 'Color', J1_col);

% Create a streaming point cloud viewer
player3D = pcplayer([-3, 3], [-3, 3], [0, 8], 'VerticalAxis', 'y', 'VerticalAxisDir', 'down');

% Visualize the point cloud
view(player3D, ptCloud);